language: python

dist: xenial

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"


install:
  - pip install -U -r requirements.txt

script:
  - scripts/test.sh
  - mypy --config-file mypy.ini pandas_to_charts

after_script:
  - codecov